name: container-image

on:
  push:
    branches: [main, p4c_pna_dev_v1, p4c_pna_dev_test]

# Cancel any preceding run on the pull request.
concurrency:
  group: container-image-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || github.ref != 'refs/heads/p4c_pna_dev_v1' || github.ref != 'refs/heads/p4c_pna_dev_test' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Determine Docker image tag
        id: get-tag
        shell: bash
        run: |
          TAG=${GITHUB_REF////_}
          echo "Tag is $TAG"
          echo "::set-output name=tag::$TAG"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
